### ISSUE TITLE
`import bokeh`

### ISSUE THREAD

**Issue by rhaas80** [chir4gm/simmonitor#1]
In 9ad192608fc92bb443ddd3e1246003ecd9aa1707

This won't work. You must specify the exact version of bokeh to use. Otherwise with the API changing or the CDN delivering a different version of the javascript parts than you used with Python, it will fail at runtime. 

See eg: https://github.com/EinsteinToolkit/tests/blob/f88536100efd719b916dfc93b383491553cc01a0/.github/workflows/main.yml#L78 and the corresponding code in the HTML template https://github.com/EinsteinToolkit/tests/blob/c85532812a6086646e1d67c98d36f169d0b830be/logpage.py#L405

**Comment by chir4gm** [comment]
changed the tool to use `plotly`. I think the requirements file for 3d should be make setup smooth.
